name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

env:
  QT_VERSION: ${{ vars.QT_VERSION }}
  QT_HOST: ${{ vars.QT_HOST }}
  QT_TARGET: ${{ vars.QT_TARGET }}
  QT_ARCH: ${{ vars.QT_ARCH }}

jobs:
  build:
    name: Build (${{ matrix.configuration }})
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        configuration:
          - Debug
          - Release

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ env.QT_HOST }}
          target: ${{ env.QT_TARGET }}
          arch: ${{ env.QT_ARCH }}
          cache: true

      - name: Show Qt Version
        shell: cmd
        run: |
          echo Qt Version: %QT_VERSION%

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake --fresh --preset vs2022-ci

      - name: Build
        shell: pwsh
        run: |
          if ("${{ matrix.configuration }}" -eq "Debug") {
              cmake --build --preset build-ci-debug --config Debug
          }
          else {
              cmake --build --preset build-ci-release --config Release
          }

      - name: Verify Executable
        shell: powershell
        run: |
          $exe = "Build/VS2022/bin/${{ matrix.configuration }}/Myelix.exe"

          if (!(Test-Path $exe)) {
              throw "Build failed. Executable not found: $exe"
          }

          Write-Host "Found $exe"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Myelix-${{ matrix.configuration }}
          path: Build/VS2022/bin/${{ matrix.configuration }}/Myelix.exe
          if-no-files-found: error
