name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  QT_VERSION: ${{ vars.QT_VERSION }}
  QT_HOST: ${{ vars.QT_HOST }}
  QT_TARGET: ${{ vars.QT_TARGET }}
  QT_ARCH: ${{ vars.QT_ARCH }}

jobs:
  build-release:
    name: Build Windows Release
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ env.QT_HOST }}
          target: ${{ env.QT_TARGET }}
          arch: ${{ env.QT_ARCH }}
          cache: true

      - name: Show Qt Version
        run: |
          echo Qt Version: %QT_VERSION%
        shell: cmd

      - name: Configure CMake
        run: cmake --preset vs2022-release

      - name: Build
        run: cmake --build --preset build-release --config Release

      - name: Verify executable
        shell: powershell
        run: |
          if (!(Test-Path "Build/VS2022/bin/Release/Myelix.exe")) {
            throw "Myelix.exe not found!"
          }

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Build/VS2022/bin/Release/Myelix.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
