name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:

    runs-on: windows-2022

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.11.1"
          host: windows
          target: desktop
          arch: win64_msvc2022_64

      - name: Configure
        run: |
          cmake --preset vs2022-release

      - name: Build
        run: |
          cmake --build --preset build-release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Build/VS2022/bin/Release/Myelix.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
